apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: logpulse-api-monitor
  namespace: logpulse
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: http-api
    path: /metrics
    interval: 15s
