apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: logpulse
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: logpulse-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: logpulse-config
        - secretRef:
            name: logpulse-secrets
