apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: logpulse
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args: ["server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000
        - containerPort: 9001
        envFrom:
        - configMapRef:
            name: logpulse-config
        - secretRef:
            name: logpulse-secrets
        volumeMounts:
        - mountPath: /data
          name: minio-data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
