apiVersion: v1
kind: ConfigMap
metadata:
  name: logpulse-config
  namespace: logpulse
data:
  # Database Settings
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "logpulse"
  
  # External Services
  REDIS_URL: "redis://redis:6379/0"
  SMTP_SERVER: "mailpit"
  SMTP_PORT: "1025"
  
  # MinIO Settings
  MINIO_ROOT_USER: "minioadmin"
  S3_ACCESS_KEY: "minioadmin"
