"""Add pseudo to user

Revision ID: 8a822dfbc9a8
Revises: e9c249726f20
Create Date: 2026-07-16 20:09:39.704044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a822dfbc9a8'
down_revision: Union[str, Sequence[str], None] = 'e9c249726f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pseudo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pseudo')
    # ### end Alembic commands ###
