"""Add image_url

Revision ID: 9bfd3766327c
Revises: 9eb00251465d
Create Date: 2026-07-17 14:03:45.321817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfd3766327c'
down_revision: Union[str, Sequence[str], None] = '9eb00251465d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'image_url')
    # ### end Alembic commands ###
