"""Add reading book and notes to journal entry

Revision ID: 9eb00251465d
Revises: 8a822dfbc9a8
Create Date: 2026-07-16 20:15:50.154716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb00251465d'
down_revision: Union[str, Sequence[str], None] = '8a822dfbc9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('reading_book', sa.String(), nullable=True))
    op.add_column('journal_entries', sa.Column('reading_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'reading_notes')
    op.drop_column('journal_entries', 'reading_book')
    # ### end Alembic commands ###
